google18-b
womendrivendev/google-oct-2018 pull request #15
Opened 2018-10-17 14:23 UTC by mahsadilmaghani

2018-10-19 12:09 UTC, MisaOgura requested changes
@mahsadilmaghani love the project!

could you add `projects/TEMPLATE.md` back in, as we need to keep it as a template :)

thanks!

2018-10-19 13:47 UTC, mahsadilmaghani commented
@MisaOgura That's great! 💃  didn't realise it's been removed - have you got it back now? :)

2018-10-20 14:45 UTC, MisaOgura commented
yep @mahsadilmaghani perfect thank you 👍

2018-10-20 14:46 UTC, MisaOgura approved these changes

2018-10-20 14:46 UTC, MisaOgura approved these changes

2018-10-20 14:49 UTC, merged